project:
  type: website

website:
  title: "CMSAC Research Lab"
  page-footer: "[![](https://www.cmu.edu/dietrich/statistics-datascience/cmsac/images/cmsac-logo-min.png){width=50%}](https://www.stat.cmu.edu/cmsac)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - papers.qmd
      - talks.qmd
      - media.qmd

format:
  html:
    theme:
      - cosmo
      - custom-theme.scss
    toc: true

execute:
  freeze: auto
