---
title: "CMSAC Research Lab"
---

Welcome to the homepage of the [Carnegie Mellon Sports Analytics Center (CMSAC)](https://www.stat.cmu.edu/cmsac/) Research Lab. We are a group of faculty and students in the [Department of Statistics & Data Science at Carnegie Mellon University](https://stat.cmu.edu/) working on developing novel, cutting-edge approaches in sports analytics across a wide range of problems. Our recent focus has been on inferring player- and team-level effects using rich spatiotemporal player tracking data.

You can check out papers by the CMSAC Research Lab on this site, along with links to talks and media articles featuring our work.

The core members of our lab include:

+ [Ron Yurko](https://www.stat.cmu.edu/~ryurko/), Assistant Teaching Professor and Director of CMSAC, Statistics & Data Science
+ [Quang Nguyen](https://qntkhvn.netlify.app/), PhD Student, Statistics & Data Science
+ Michele Sezgin, PhD Student, Statistics & Data Science
+ Meg Ellingwood, PhD Student, Statistics & Data Science
+ Ruitong (Larry) Jiang, PhD Student, Neuroscience
+ Alex Williams, PhD Student, Economics
+ [Sam Ventura](https://www.cmu.edu/dietrich/statistics-datascience/people/affiliated/sam-ventura.html), Affiliated Faculty, and Vice President of Hockey Strategy and Research, Buffalo Sabres